### ISSUE TITLE
Issue concerning  jinja2.exceptions.TemplateNotFound: main.jinja

### ISSUE THREAD

**Issue by mmolero** [samuelcolvin/notbook#3]
First it all, the project looks awesome, thanks for sharing!!!

I wanted to run by myself however I found the following issue:

> (python38) miguel@lena2:~/Documents/libs/notbook/scripts$ notbook build simple.py 
> executing simple.py and saving output to site...
> Traceback (most recent call last):
>   File "/home/miguel/anaconda3/envs/python38/bin/notbook", line 11, in <module>
>     load_entry_point('notbook==0.0.1', 'console_scripts', 'notbook')()
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/typer-0.2.1-py3.8.egg/typer/main.py", line 213, in __call__
>     return get_command(self)()
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/typer-0.2.1-py3.8.egg/typer/main.py", line 496, in wrapper
>     return callback(**use_params)  # type: ignore
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/notbook-0.0.1-py3.8.egg/notbook/cli.py", line 25, in build
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/notbook-0.0.1-py3.8.egg/notbook/main.py", line 22, in build
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/notbook-0.0.1-py3.8.egg/notbook/render.py", line 23, in render
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
>     source, filename, uptodate = self.get_source(environment, name)
>   File "/home/miguel/anaconda3/envs/python38/lib/python3.8/site-packages/jinja2/loaders.py", line 249, in get_source
>     raise TemplateNotFound(template)
> jinja2.exceptions.TemplateNotFound: main.jinja

I create a new enviroment with Anaconda and python3.8  but I got the above issue. 
Could you figure it out what happened?

Thanks!!!

I have installed using the classic way: 

```
python setup.py build
python setup.py install
```

**Comment by samuelcolvin** [comment]
Did it work installing the classic way?

I used `pip install .`, maybe try that.

**Comment by samuelcolvin** [comment]
I'm using

https://github.com/samuelcolvin/notbook/blob/90378498365f1e62c43f5bd79ca43cc1fb8be242/notbook/render.py#L36

`PackageLoader` is probably the culprit.

**Comment by mmolero** [comment]
Thanks for the quick reply,
I tried to use `pip install .` but nothing, I got the same error, I did with a clean enviroment to test it.

**Comment by mmolero** [comment]
these are my dependences:

> name: python38
> channels:
>   - defaults
> dependencies:
>   - _libgcc_mutex=0.1=main
>   - ca-certificates=2020.1.1=0
>   - certifi=2020.4.5.1=py38_0
>   - libedit=3.1.20181209=hc058e9b_0
>   - libffi=3.2.1=hd88cf55_4
>   - libgcc-ng=9.1.0=hdf63c60_0
>   - libstdcxx-ng=9.1.0=hdf63c60_0
>   - ncurses=6.2=he6710b0_1
>   - openssl=1.1.1g=h7b6447c_0
>   - pip=20.0.2=py38_3
>   - python=3.8.0=h0371630_2
>   - readline=7.0=h7b6447c_5
>   - setuptools=46.2.0=py38_0
>   - sqlite=3.31.1=h62c20be_1
>   - tk=8.6.8=hbc83047_0
>   - wheel=0.34.2=py38_0
>   - xz=5.2.5=h7b6447c_0
>   - zlib=1.2.11=h7b6447c_3
>   - pip:
>     - aiohttp==3.6.2
>     - async-timeout==3.0.1
>     - attrs==19.3.0
>     - cffi==1.14.0
>     - chardet==3.0.4
>     - click==7.1.2
>     - devtools==0.5.1
>     - idna==2.9
>     - jinja2==2.11.2
>     - markupsafe==1.1.1
>     - misaka==2.1.1
>     - multidict==4.7.6
>     - notbook==0.0.1
>     - pycparser==2.20
>     - pygments==2.6.1
>     - typer==0.2.1
>     - watchgod==0.6
>     - yarl==1.4.2

**Comment by samuelcolvin** [comment]
I know what it is! I forgot to add the templates as package files.

Clone the repo, then install with `pip install -e .` and it should work. I'll fix tomorrow.
